[bench_data."Oh-My-ZSH"]
mean_time_ms = 1590.0
first_prompt_lag_ms = 23.933
first_command_lag_ms = 1394.707
command_lag_ms = 26.280
input_lag_ms = 20.930
exit_time_ms = 1289.902

[bench_data."Zinit Light"]
mean_time_ms = 296.9
first_prompt_lag_ms = 23.272
first_command_lag_ms = 396.356
command_lag_ms = 23.035
input_lag_ms = 21.773
exit_time_ms = 293.687

[bench_data."Zinit Turbo"]
mean_time_ms = 223.9
first_prompt_lag_ms = 23.769
first_command_lag_ms = 268.712
command_lag_ms = 22.835
input_lag_ms = 20.813
exit_time_ms = 212.760

# [bench_data."Zinit Turbo + Defer"]
# mean_time_ms = 86.6
# first_prompt_lag_ms = 23.554
# first_command_lag_ms = 137.714
# command_lag_ms = 22.860
# input_lag_ms = 20.358
# exit_time_ms = 81.634

[bench_data.Zim]
mean_time_ms = 164.3
first_prompt_lag_ms = 22.964
first_command_lag_ms = 271.194
command_lag_ms = 22.392
input_lag_ms = 19.789
exit_time_ms = 171.173

[bench_data."我的設定"]
mean_time_ms = 42.9
first_prompt_lag_ms = 24.194
first_command_lag_ms = 98.126
command_lag_ms = 23.173
input_lag_ms = 22.092
exit_time_ms = 43.568

[bench_data."Baseline (Empty .zshrc)"]
mean_time_ms = 11.1
first_prompt_lag_ms = 16.612
first_command_lag_ms = 16.776
command_lag_ms = 0.071
input_lag_ms = 0.199
exit_time_ms = 15.626
