[bench_data.Oh-My-ZSH]
first_prompt_lag_ms = 23.718
first_command_lag_ms = 209.631
command_lag_ms = 17.940
input_lag_ms = 20.518
exit_time_ms = 377.806

[bench_data.Zinit]
first_prompt_lag_ms = 16.408
first_command_lag_ms = 88.077
command_lag_ms = 15.466
input_lag_ms = 12.771
exit_time_ms = 42.832

[bench_data."No Plugin Manager"]
first_prompt_lag_ms = 23.367
first_command_lag_ms = 78.865
command_lag_ms = 15.794
input_lag_ms = 15.877
exit_time_ms = 30.441

[bench_data.Zim]
first_prompt_lag_ms = 18.633
first_command_lag_ms = 75.597
command_lag_ms = 15.183
input_lag_ms = 14.785
exit_time_ms = 29.204

[bench_data."This dotfile"]
first_prompt_lag_ms = 20.697
first_command_lag_ms = 79.508
command_lag_ms = 16.337
input_lag_ms = 12.071
exit_time_ms = 30.972

[bench_data."Baseline (No .zshrc)"]
first_prompt_lag_ms = 14.343
first_command_lag_ms = 14.479
command_lag_ms = 0.064
input_lag_ms = 0.201
exit_time_ms = 15.237
