#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e
SRC_ROOT="${SRC_ROOT:-$( cd -- "$(dirname "$0")/.." >/dev/null 2>&1 ; pwd -P)}"

if [[ "$(uname)" == "Darwin" ]]; then
  find $SRC_ROOT/installer -maxdepth 1 -mindepth 1 -type f -name "*.sh" -exec echo "Executing: {}" \; -exec bash -c 'source "$0"' {} \;
else
  find $SRC_ROOT/installer -maxdepth 1 -mindepth 1 -type f -name "*.sh" ! -name "macos-*.sh" -exec echo "Executing: {}" \; -exec bash -c 'source "$0"' {} \;
fi
